# Generated by Django 3.2.9 on 2021-11-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('address', models.CharField(error_messages={'unique': 'This address is already registered'}, max_length=256, unique=True)),
                ('tokenBalance', models.FloatField(default=0)),
                ('dollarBalance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('bio', models.TextField()),
                ('itemUrl', models.CharField(max_length=5000)),
                ('itemHash', models.CharField(blank=True, max_length=256)),
                ('startingPrice', models.FloatField(default=0)),
                ('tokenOffer', models.FloatField(blank=True, default=0, null=True)),
                ('fee', models.FloatField(blank=True, default=0, null=True)),
                ('endingAuction', models.DateTimeField()),
                ('creatorAddress', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
